#!/bin/bash

#----------------------------------------------------------------------------------------------------------------
#                                                                                                            Info
#----------------------------------------------------------------------------------------------------------------
# name: ExportListDistr
# version: 1.0
# autor: joseRomera <web@joseromera.net>
# web: http://www.joseromera.net
# Copyright (C) 2020
#----------------------------------------------------------------------------------------------------------------
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#----------------------------------------------------------------------------------------------------------------


#----------------------------------------------------------------------------------------------------------------
#                                                                                                       Variables
#----------------------------------------------------------------------------------------------------------------
COS=$(echo "displayName zimbraCreateTimestamp zimbraId members")
PATH=/tmp/ExportListDistr


#----------------------------------------------------------------------------------------------------------------
#                                                                                                       Funciones
#----------------------------------------------------------------------------------------------------------------
# Comprobar carpeta exite
if [ -d "$PATH" ]; then
  echo "Installing config files in ${PATH}..."
else
  mkdir $PATH
fi

for i in `zmprov gadl` ; do 
 RESULTADO=`zmprov gdl $i  $COS | grep -v "#" | awk '{print $2";"}'|tr -d '\n' | head -c-2`; 
 echo $i ";" $RESULTADO >> $PATH/ExportListDistr.csv
done 
